# permissions to do viewer kcertifiers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kcertifier-viewer-role
rules:
- apiGroups:
  - kcertifier.atteg.com
  resources:
  - kcertifiers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kcertifier.atteg.com
  resources:
  - kcertifiers/status
  verbs:
  - get
